{{- $componentValues := .Values.catalog }}
{{- if and $componentValues.enabled $componentValues.config }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "otel-demo.resourceName" (dict "ctx" . "component" "catalog") }}-config
  namespace: {{ include "otel-demo.namespace" . }}
  labels:
    {{- include "otel-demo.labels" (dict "ctx" . "component" "catalog") | nindent 4 }}
  {{- with .Values.global.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  {{ $componentValues.config.fileName | default "application-kubernetes.properties" }}: |
    spring.datasource.url=jdbc:postgresql://{{ include "otel-demo.postgresql.host" . }}:{{ include "otel-demo.postgresql.port" . }}/{{ include "otel-demo.postgresql.database" . }}?useUnicode=yes&characterEncoding=UTF-8&serverTimezone=UTC
    spring.datasource.username={{ include "otel-demo.postgresql.username" . }}
    spring.datasource.password={{ include "otel-demo.postgresql.password" . }}
    cloud.aws.region.static={{ .Values.aws.region }}
    cloud.aws.s3.bucket-name={{ .Values.aws.s3.bucketName }}
    minio.enabled=false
    spring.rabbitmq.host={{ include "otel-demo.rabbitmq.host" . }}
    spring.rabbitmq.port={{ include "otel-demo.rabbitmq.port" . }}
    spring.rabbitmq.username=guest
    spring.rabbitmq.password=guest
{{- end }}
