apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-catalog-sa
  namespace: {{.Values.namespace}}
  labels:
    app: {{ .Release.Name }}-catalog
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.catalog.serviceAccount.role }}