CREATE TABLE IF NOT EXISTS images
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    file_name    VARCHAR                                 NOT NULL,
    url          VARCHAR,
    content_type VARCHAR,
    size         BIGINT                                  NOT NULL,
    CONSTRAINT pk_images PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS products
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR,
    description VARCHAR,
    price       DOUBLE PRECISION                        NOT NULL,
    image       BIGINT GENERATED BY DEFAULT AS IDENTITY,
    CONSTRAINT pk_products PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS inventory
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    product_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    quantity   INTEGER                                 NOT NULL,
    CONSTRAINT pk_inventory PRIMARY KEY (id)
);

ALTER TABLE products
    ADD CONSTRAINT uc_products_image UNIQUE (image);

ALTER TABLE products
    ADD CONSTRAINT FK_PRODUCTS_ON_IMAGE FOREIGN KEY (image) REFERENCES images (id);


ALTER TABLE inventory
    ADD CONSTRAINT uc_inventory_product UNIQUE (product_id);

ALTER TABLE inventory
    ADD CONSTRAINT FK_INVENTORY_ON_PRODUCT FOREIGN KEY (product_id) REFERENCES products (id);