CREATE TABLE images
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    file_name    VARCHAR                                 NOT NULL,
    url          VARCHAR,
    content_type VARCHAR,
    size         BIGINT                                  NOT NULL,
    CONSTRAINT pk_images PRIMARY KEY (id)
);

CREATE TABLE products
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR,
    description VARCHAR,
    price       DOUBLE PRECISION                        NOT NULL,
    image       BIGINT GENERATED BY DEFAULT AS IDENTITY,
    CONSTRAINT pk_products PRIMARY KEY (id)
);

ALTER TABLE products
    ADD CONSTRAINT uc_products_image UNIQUE (image);

ALTER TABLE products
    ADD CONSTRAINT FK_PRODUCTS_ON_IMAGE FOREIGN KEY (image) REFERENCES images (id);