---
services:
  postgres:
    image: postgres:16
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: shop
      POSTGRES_USER: backend
      POSTGRES_PASSWORD: "pass"
      PGDATA: /var/lib/postgresql/data/
    volumes:
      - postgres-storage:/var/lib/postgresql/
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}'" ]
      interval: 1m
      timeout: 10s
      retries: 5
      start_period: 45s
    networks:
      demo:

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
    volumes:
      - datastore:/data
    environment:
      - "MINIO_ACCESS_KEY=minio"
      - "MINIO_SECRET_KEY=minio123"
    command: server /data

  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://minio:9000 minio minio123;
      /usr/bin/mc mb myminio/catalog;
      exit 0;
      "

  redis:
    image: redis:7.4.0-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  rabbitmq:
    image: rabbitmq:3.13-management
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: "admin"
      RABBITMQ_DEFAULT_PASS: "admin"
    volumes:
      - rabbitmq-storage:/var/lib/rabbitmq

  tempo:
    image: grafana/tempo:2.9.0
    container_name: tempo
    command:
      - "-config.file=/etc/tempo-config/tempo.yaml"
      - "-storage.trace.backend=local"
      - "-storage.trace.local.path=/tmp/tempo/traces"
      - "-storage.trace.wal.path=/tmp/tempo/wal"
      - "-auth.enabled=false"
      - "-server.http-listen-port=3200"
    restart: unless-stopped
    volumes:
      - ${PWD}/telemetry/tempo.yaml:/etc/tempo-config/tempo.yaml
    networks:
      demo:

  mimir:
    image: grafana/mimir:2.17.4
    container_name: mimir
    restart: unless-stopped
    command:
      - -config.file=/etc/mimir-config/mimir.yaml
    volumes:
      - ${PWD}/telemetry/mimir.yaml:/etc/mimir-config/mimir.yaml
    networks:
      demo:

  loki:
    image: grafana/loki:3.6.3
    container_name: loki
    restart: unless-stopped
    ports:
      - "3100:3100"
    networks:
      demo:

  grafana:
    container_name: grafana
    image: grafana/grafana:12.0.2
    restart: unless-stopped
    environment:
      - "GF_INSTALL_PLUGINS=grafana-opensearch-datasource"
    volumes:
      - ./telemetry/grafana/provisioning/:/etc/grafana/provisioning/
      - "grafana-storage:/var/lib/grafana"
    ports:
      - "3000:3000"
    networks:
      demo:

  # OpenTelemetry Collector
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.143.1
    container_name: otel-collector
    deploy:
      resources:
        limits:
          memory: 200M
    restart: unless-stopped
    command: [ "--config=/etc/otelcol-config.yml"]
    user: 0:0
    volumes:
      - /:/hostfs:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./telemetry/otel-collector-config.yml:/etc/otelcol-config.yml
    ports:
      - "4317:4317"
      - "4318:4318"
    depends_on:
      tempo:
        condition: service_started
    networks:
      demo:

volumes:
  postgres-storage:
  datastore:
  redis-data:
  rabbitmq-storage:
  grafana-storage:

networks:
  demo:
