apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-checkout-config
  namespace: {{.Values.namespace}}
data:
  config.yml: |
    port: "8082"
    catalog:
      protocol: "http"
      server: "{{.Release.Name}}-catalog.otel-demo"
      port: 80
      path: ""
      timeout: "3"

    cart:
      protocol: "http"
      server: "{{.Release.Name}}-cart.otel-demo"
      port: "80"
      path: "/api/v1"
      timeout: "3"

    rabbitmq:
      host: "rabbitmq.otel-demo"
      port: 5672
      username: default_user_12RrN5uEezynHe88C5X
      password: OyUyPcH1wxtAJotqH4nwpO4MQhTHieMn
      exchange: inventory_update

    telemetry:
      enabled: true
      collector_url: opentelemetry-demo-otelcol
      collector_port: 4317
