apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-checkout
  namespace: {{.Values.namespace}}
spec:
  selector:
    app: {{ .Release.Name }}-checkout
  ports:
    - name: http
      port: 80
      targetPort: 8082
  type: NodePort