receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

  docker_stats:
    endpoint: unix:///var/run/docker.sock

  postgresql:
    endpoint: "postgres:5432"
    username: "backend"
    password: "pass"
    tls:
      insecure: true
  redis:
    endpoint: "redis:6379"
    collection_interval: 10s

exporters:
  debug:
  otlp/tempo:
    endpoint: tempo:4317
    tls:
      insecure: true
  otlphttp/mimir:
    endpoint: "http://mimir:9009/otlp"
  otlphttp/loki:
    endpoint: "http://loki:3100/otlp"
processors:
  batch:
  memory_limiter:
    check_interval: 5s
    limit_percentage: 80
    spike_limit_percentage: 25
  resourcedetection:
    detectors: [ env, docker, system ]
  transform:
    error_mode: ignore
    trace_statements:
      - context: span
        statements:
          # could be removed when https://github.com/vercel/next.js/pull/64852 is fixed upstream
          - replace_pattern(name, "\\?.*", "")
          - replace_match(name, "GET /api/products/*", "GET /api/products/{productId}")

connectors:
  spanmetrics:


service:
  pipelines:
    traces:
      receivers: [ otlp ]
      processors: [ resourcedetection, memory_limiter, transform, batch ]
      exporters: [ otlp/tempo, debug, spanmetrics ]
    metrics:
      receivers: [ docker_stats, otlp, postgresql, redis, spanmetrics ]
      processors: [ resourcedetection, memory_limiter, batch ]
      exporters: [ otlphttp/mimir, debug ]
    logs:
      receivers: [ otlp ]
      processors: [ resourcedetection, memory_limiter, batch ]
      exporters: [ otlphttp/loki, debug ]
