apiVersion: v2
name: aws-skg-meetup-demo
description: A Helm chart for deploying the Opentelemetry Demo Project from the AWS SKG Meetup

type: application

version: 0.1.0

appVersion: "1.0.0"

#dependencies:
#  - name: postgresql
#    version: "15.5.32"
#    repository: "https://charts.bitnami.com/bitnami"
#  - name: opentelemetry-collector
#    version: "0.106.0"
#    repository: "https://open-telemetry.github.io/opentelemetry-helm-charts"
#  - name: prometheus
#    version: "15.4.0"
#    repository: "https://prometheus-community.github.io/helm-charts"
#  - name: lgtm-distributed
#    version: "2.1.0"
#    repository: "https://grafana.github.io/helm-charts"
