apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-frontend-config
  namespace: {{.Values.namespace}}
data:
  .env: |
    CATALOG_SERVICE_ADDR: "http://k8s-oteldemo-appingre-cbd2f9aac5-1354783183.eu-west-1.elb.amazonaws.com"
    CART_SERVICE_ADDR: "http://k8s-oteldemo-appingre-cbd2f9aac5-1354783183.eu-west-1.elb.amazonaws.com"
    CHECKOUT_SERVICE_ADDR: "http://k8s-oteldemo-appingre-cbd2f9aac5-1354783183.eu-west-1.elb.amazonaws.com"
    OTEL_EXPORTER_OTLP_ENDPOINT: "http://opentelemetry-demo-otelcol:4317"
    OTEL_METRICS_EXPORTER: "otlp"
    OTEL_TRACES_EXPORTER: "otlp"
    IMAGE_SERVER_PROTOCOL: "https"
    IMAGE_SERVER_HOST: "s3.eu-west-1.amazonaws.com"
    IMAGE_SERVER_PORT: "443"
    IMAGE_SERVER_BUCKET: "aws-skg-otel-demo-catalog-pkarakal"
